support .d and disable beeswarm
bigbio/pmultiqc pull request #90
Opened 2023-10-26 15:20 UTC by daichengxin

2023-10-26 17:42 UTC, ypriverol commented
@daichengxin is this also supporting DDA data or is only for DIA `.d` ?

2023-10-26 17:51 UTC, ypriverol requested changes

2023-10-26 17:51 UTC, ypriverol commented on setup.py
> +version = '0.1.0'
I think we can continue increasing the version to 0.0.23 until we feel this is a nice release version.

2023-10-27 04:31 UTC, daichengxin commented
> @daichengxin is this also supporting DDA data or is only for DIA `.d` ?

It also supports DDA

2023-10-27 07:37 UTC, ypriverol approved these changes

2023-10-27 07:37 UTC, merged